In [54]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier


In [39]:
data=pd.read_csv(r'C:\Users\bathma\Desktop\short squeeze stock data.csv')
data.head()

Datetime  Open    High     Low   Close  Volume Symbol
0  44502.40  3.37  3.3700  3.3700  3.3700   175.0   PPSI
1  44502.40  3.36  3.3600  3.3300  3.3300  1889.0   PPSI
2  44502.41  3.33  3.3932  3.3296  3.3932  2630.0   PPSI
3  44502.41  3.33  3.3300  3.3200  3.3200  1350.0   PPSI
4  44502.41  3.33  3.3300  3.3300  3.3300   173.0   PPSI

In [30]:
X=data.iloc[:,:-1].values
y=data.iloc[:,6].values

In [49]:
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,test_size=0.3)


In [50]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50229 entries, 0 to 50228
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Datetime  50229 non-null  float64
 1   Open      50229 non-null  float64
 2   High      50229 non-null  float64
 3   Low       50229 non-null  float64
 4   Close     50229 non-null  float64
 5   Volume    50229 non-null  float64
 6   Symbol    50229 non-null  object 
dtypes: float64(6), object(1)
memory usage: 2.7+ MB


In [48]:
classifier=RandomForestClassifier(n_estimators=50)
classifier.fit(Xtrain,ytrain)

RandomForestClassifier(n_estimators=50)

In [51]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
ypre=classifier.predict(Xtest)
result=confusion_matrix(ytest,ypre)
print('confusion matrix')
print('----------------')
print(result)


confusion matrix
----------------
[[1369    0    0    0    0    0    0    0]
 [   0 1930    0    0    0    0    0    0]
 [   0    0 1186    0    0    0    0    0]
 [   0    0    1 1791    0    2    0    0]
 [   0    0    0    0 1977    0    0    0]
 [   0    0    0    0    2 3229    0    0]
 [   0    0    0    0    0    1 2061    1]
 [   0    0    0    0    0    0    0 1519]]


In [52]:
result1=accuracy_score(ytest,ypre)
print('accuracy score')
print('----------------')
print(result1)

accuracy score
----------------
0.9995354701705488


In [53]:
result2=classification_report(ytest,ypre)
print('classification report')
print('----------------')
print(result2)

classification report
----------------
              precision    recall  f1-score   support

        BMTX       1.00      1.00      1.00      1369
         GME       1.00      1.00      1.00      1930
        ISPC       1.00      1.00      1.00      1186
        LGVN       1.00      1.00      1.00      1794
        PPSI       1.00      1.00      1.00      1977
        PROG       1.00      1.00      1.00      3231
        PTPI       1.00      1.00      1.00      2063
        QLGN       1.00      1.00      1.00      1519

    accuracy                           1.00     15069
   macro avg       1.00      1.00      1.00     15069
weighted avg       1.00      1.00      1.00     15069

